version: "3.9"
services:
  postgres:
    image: postgres:14.7
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: rulessystem
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
