"""Creating Rule Action Table

Revision ID: 952a9d081a0a
Revises: b34395740909
Create Date: 2023-12-17 22:25:48.637348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision: str = '952a9d081a0a'
down_revision: Union[str, None] = 'b34395740909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    action_enum = ENUM('webhook', 'email', 'fulfillment',
                       name='rule_action_enum', 
                       create_type=False)
    action_enum.create(op.get_bind(), checkfirst=True)
    
    op.create_table(
        'rule_action',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('action', action_enum, nullable=False),
        sa.Column('data', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_action')
    # ### end Alembic commands ###
