"""Creating Rule Table

Revision ID: b34395740909
Revises: 
Create Date: 2023-12-15 15:23:14.179910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import rules_system.types as rs


# revision identifiers, used by Alembic.
revision: str = 'b34395740909'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'rule',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('entity', sa.String(), nullable=False),
        sa.Column('filters', rs.JSONB(), nullable=False),
        sa.Column('actions', rs.ARRAY(), nullable=False),
        sa.Column('enabled', sa.Boolean(), nullable=False),
        
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule')
    # ### end Alembic commands ###